---
- name: Query current people in space (astros.json)
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - name: Call open-notify astronauts API
      ansible.builtin.uri:
        url: http://api.open-notify.org/astros.json
        method: GET
        return_content: true
        status_code: 200
        headers:
          Accept: application/json
      register: astros

    - name: Show raw JSON (for troubleshooting)
      ansible.builtin.debug:
        msg: "{{ astros.json.people | map(attribute='name') }}"

